name: PR Tests

on:
  pull_request:
    branches: [ "main" ]  # o la rama que uses (develop, etc.)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Permisos a mvnw
        run: chmod +x mvnw

      - name: Ejecutar pruebas
        run: ./mvnw test